version: '2.4'
services:
    Devshift.Authentication.Api:
        container_name: Devshift.Authentication.Api
        environment:
            ASPNETCORE_ENVIRONMENT: Production
            ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
            TZ: Asia/Bangkok
        cpus: 1
        mem_limit: 1gb
        network_mode: bridge
        volumes:
            - ../secrets/secrets.json:/app/secrets.json
            - ../secrets/Certs/client-cert.pem:/app/Certs/client-cert.pem
            - ../secrets/Certs/client-key.pem:/app/Certs/client-key.pem
            - ../secrets/Certs/ap-southeast-1-bundle.pem:/app/Certs/ap-southeast-1-bundle.pem
            - ../secrets/Certs/nio.crt:/usr/local/share/ca-certificates/nio.crt
        image: {{ DOCKER_IMAGE }}        
        logging:
            driver: fluentd
            options:
              tag: dotnet
        ports:
            - "32003:32003"
        restart: unless-stopped
        ulimits:
            core: 0